'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {Game,Timeline,Follower,STEP,MAX_SPEED,MAX_ACCEL,readProgress}=require('../core.js');
const {driver}=require('./routes.cjs');
test('single fresh phase sample never yields nonfinite interpolation at floating-point boundary',()=>{const t=new Timeline();t.add(13.125,{x:500,y:300});const p=t.at(13.125-1e-12);assert.equal(p.x,500);assert.equal(p.y,300);});
test('replay button edges snap floating-point dust, not genuine earlier input',()=>{const t=new Timeline();t.add(1,{x:0,y:0,down:false});t.add(1+STEP,{x:1,y:1,down:true});t.add(1+STEP*2,{x:2,y:2,down:false});assert.equal(t.at(1+STEP-1e-12).down,true);assert.equal(t.at(1+STEP-1e-5).down,false);assert.equal(t.at(1+STEP*2-1e-12).down,false);assert.equal(t.at(1+STEP*2-1e-5).down,true);});
test('timestamp interpolation replays position and button exactly two seconds later',()=>{const t=new Timeline();t.add(0,{x:0,y:0,down:true});t.add(1,{x:100,y:50,down:false});assert.deepEqual(t.at(.5),{t:.5,x:50,y:25,down:true});assert.equal(t.at(-.1),null);const g=new Game();for(let n=1;n<=480;n++)g.update(STEP,{x:n*STEP*100,y:600,down:n*STEP<2.5});assert.ok(Math.abs(g.echo.x-200)<1e-6);assert.equal(g.echo.down,true);});
test('fixed physics identical at 30, 60, 144 FPS, reduced motion is not physics',()=>{const out=[30,60,144].map(fps=>{const g=new Game(),f=new Follower(g.point);let a=0;for(let frame=0;frame<fps*4;frame++){a+=1/fps;while(a+1e-9>=STEP){const t=g.t+STEP;g.update(STEP,f.update(STEP,{x:600+Math.sin(t)*200,y:550}));a-=STEP;}}return [g.t,g.point.x,g.echo.x];});assert.deepEqual(out[0],out[1]);assert.deepEqual(out[1],out[2]);});
test('follower speed and acceleration are bounded, with no overshoot or tiny hand-jitter beads',()=>{const f=new Follower({x:0,y:0});let x=0,vx=0,vy=0;for(let i=0;i<480;i++){const p=f.update(STEP,{x:500,y:300});assert.ok(p.x>=x&&p.x<=500);assert.ok(Math.hypot(f.vx,f.vy)<=MAX_SPEED+1e-7);assert.ok(Math.hypot(f.vx-vx,f.vy-vy)<=MAX_ACCEL*STEP+.5);x=p.x;vx=f.vx;vy=f.vy;}assert.ok(Math.abs(x-500)<.03);const samples=[];for(let i=0;i<120;i++)samples.push(f.update(STEP,{x:500+(i%2?1.5:-1.5),y:300}).x);assert.ok(Math.max(...samples)-Math.min(...samples)<.2);});
test('early clicks are never queued; only explicit memory powers the door until release',()=>{const d=driver(0),g=d.g;d.tap(g.level.exit);assert.equal(g.won,false);d.move(g.level.seal,3);d.tap(g.level.exit);assert.equal(g.won,false);d.pin(g.level.seal);d.move(g.level.exit,60);assert.equal(g.open,true);assert.equal(g.won,false);d.release();d.click();assert.equal(g.won,false);assert.equal(g.open,false);d.pin(g.level.seal);d.tap(g.level.exit);assert.equal(g.won,true);});
test('checkpoint retains logical choices and rebuilds memory, never a partial timeline',()=>{const d=driver(1),R=require('../rules.js');d.tap(R.magicLayout().mirrors[0]);d.pin(R.magicLayout().source);const fresh=new Game(1,d.g.checkpoint());assert.deepEqual(fresh.state.orientations,[1,0]);assert.equal(fresh.state.phase,0);assert.equal(fresh.memory,null);assert.equal(fresh.pending.id,'source');assert.equal(fresh.echo,null);assert.equal(fresh.open,false);assert.equal(fresh.timeline.samples.length,1);assert.deepEqual(fresh.contacts,{});for(let i=0;i<239;i++)fresh.update(1/120,fresh.point);assert.equal(fresh.memory,null);fresh.update(1/120,fresh.point);assert.equal(fresh.memory.id,'source');});
test('timeline bounded and pause contributes no samples or elapsed game time',()=>{const g=new Game();for(let n=0;n<4800;n++)g.update(STEP,{x:20,y:600});const before=JSON.stringify(g);const f=new Follower(g.point);for(let i=0;i<1200;i++)f.update(STEP,{x:500,y:100});assert.equal(JSON.stringify(g),before);assert.ok(g.timeline.samples.length<390);});
test('new progress validates inputs independently of old storage',()=>{assert.deepEqual(readProgress(null),{completed:[],unlocked:0,current:0,started:false,checkpoints:{}});const p=readProgress({completed:[-1,7,7,'1'],unlocked:999,current:999,checkpoints:{0:{phase:999}}});assert.deepEqual(p.completed,[7]);assert.equal(p.unlocked,7);assert.equal(p.checkpoints[0],undefined);});
test('modest speed boost is shared and preserves the precise two-second replay',()=>{
 assert.equal(MAX_SPEED,420);assert.equal(MAX_ACCEL,1600);
 const g=new Game(),f=new Follower(g.point),samples=new Map();
 for(let n=1;n<=720;n++){
  const target=n<160?{x:1020,y:480}:n<360?{x:300,y:280}:{x:820,y:420};
  g.update(STEP,f.update(STEP,{...target,down:n>=200&&n<450}));samples.set(n,{...g.point});
  if(n>240){const past=samples.get(n-240);assert.ok(Math.hypot(g.echo.x-past.x,g.echo.y-past.y)<1e-6);assert.equal(g.echo.down,past.down);}
 }
});
