'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{Rules:R,Game}=require('../core.js'),{driver,solve}=require('./routes.cjs');
test('temperance anticipatory departure lets the past finish half a cup',()=>{const d=driver(3);d.until(()=>d.g.effect.forecast>=55,R.spring);const before=d.g.state.water;assert.ok(before<54);d.move(R.rest,5);assert.equal(d.g.won,true);assert.ok(d.g.state.water>=54&&d.g.state.water<=66);});
test('waiting for actual half-cup overshoots, then can drain and retry without restarting chapter',()=>{const d=driver(3);d.until(()=>d.g.state.water>=60,R.spring);d.move(R.rest,5);assert.equal(d.g.won,false);assert.ok(d.g.state.water>66);d.tap(R.vessel);assert.equal(d.g.state.water,0);assert.equal(d.g.echo,null);assert.equal(solve(d,3).won,true);});
test('too short a pour cannot be banked into success at rest',()=>{const d=driver(3);d.move(R.spring,1);d.move(R.rest,5);assert.equal(d.g.won,false);assert.ok(d.g.state.water<54);});
test('pour forecast matches final water after all recorded input replays',()=>{const d=driver(3);d.move(R.spring,2);d.move({x:350,y:520},.8);const predicted=d.g.effect.forecast;d.move({x:350,y:520},3);assert.ok(Math.abs(predicted-d.g.state.water)<.3);});
test('clearing an echo clears pending water so no old pulse contaminates a retry',()=>{const d=driver(3);d.move(R.spring,1.8);d.move({x:350,y:520},.8);d.release();d.move(R.rest,4);assert.equal(d.g.state.water,0);assert.equal(d.g.won,false);assert.equal(d.g.memory,null);});
test('water and unfinished pulse are intentionally not saved; settings and solved edges are separate',()=>{const d=driver(3);d.move(R.spring,2);const g=new Game(3,d.g.checkpoint());assert.equal(g.state.water,0);assert.deepEqual(g.state.pourSamples,[]);assert.equal(g.echo,null);});
test('undo cannot resurrect drained water without its pending echo pulse',()=>{const d=driver(3);d.until(()=>d.g.state.water>=60,R.spring);d.tap(R.vessel);assert.equal(d.g.history.length,0);assert.equal(d.g.undo(),false);assert.equal(d.g.state.water,0);});
